# Generated by Django 3.2.5 on 2021-11-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('여자', '여'), ('남자', '남')], max_length=10)),
                ('sickness', models.TextField(blank=True, max_length=300, null=True)),
                ('recent_problem', models.TextField(blank=True, max_length=300, null=True)),
                ('bed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.bed')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_loc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.bed')),
            ],
        ),
        migrations.CreateModel(
            name='OccupancyGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.elder')),
            ],
        ),
        migrations.CreateModel(
            name='ElderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=15)),
                ('lay', models.IntegerField()),
                ('sit', models.IntegerField()),
                ('empty', models.IntegerField()),
                ('recent_status', models.CharField(max_length=10)),
                ('today_status', models.CharField(max_length=10)),
                ('max_status', models.CharField(max_length=10)),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.elder')),
            ],
        ),
        migrations.AddField(
            model_name='elder',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.room'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.room'),
        ),
    ]
